name: Bug report
description: File a new Bug
title: '[Bug]: '
body:
  - type: input
    attributes:
      label: Description
      description: A brief description of what happened.
      placeholder: Something went wrong!
    validations:
      required: true
  - type: input
    attributes:
      label: What operating system are you using?
      description: e.g. Windows 11 (24H2), Ubuntu 24.04, macOS Ventura (13.6.7)
  - type: input
    attributes:
      label: What browser are you using?
      description: 'Examples: Microsoft Edge (126.0.2592.87), Mozilla Firefox (127.0.2)'
  - type: dropdown
    attributes:
      label: Are you using a VPN or Proxy?
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: What else can you tell us?
    validations:
      required: true
